
language: python

python:
 - "3.6"

install:
 - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database ireporter;' -U postgres
  #- psql -c "CREATE USER postgres WITH PASSWORD 'Nanbada13';" -U postgres

script:
- nosetests --with-coverage --cover-package=app

after_success: 
  - coveralls


